# Generated by Django 5.2 on 2025-05-27 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overrideuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['-date_joined'], 'verbose_name': 'usuario', 'verbose_name_plural': 'usuarios'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='direccion',
            field=models.CharField(blank=True, default='', help_text='Dirección de residencia', max_length=255),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='telefono',
            field=models.CharField(blank=True, default='', help_text='Número de teléfono de contacto', max_length=20),
        ),
    ]
