# Generated by Django 4.2.20 on 2025-05-12 20:17

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="categoria",
            name="imagen",
            field=models.ImageField(blank=True, null=True, upload_to="categorias/"),
        ),
    ]
