# Generated by Django 5.2 on 2025-05-28 22:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carritos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'carrito',
                'verbose_name_plural': 'carritos',
                'ordering': ['-actualizado'],
            },
        ),
        migrations.CreateModel(
            name='ItemCarrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1, help_text='Cantidad de unidades del producto')),
                ('precio', models.DecimalField(decimal_places=2, help_text='Precio unitario al momento de agregar al carrito', max_digits=10)),
                ('descripcion', models.CharField(blank=True, help_text='Descripción adicional del producto', max_length=255)),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='carrito.carrito')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='en_carritos', to='productos.producto')),
            ],
            options={
                'verbose_name': 'ítem del carrito',
                'verbose_name_plural': 'ítems del carrito',
                'ordering': ['producto__nombre'],
                'constraints': [models.UniqueConstraint(fields=('carrito', 'producto'), name='unique_producto_en_carrito')],
            },
        ),
    ]
