# Generated by Django 5.2 on 2025-05-27 00:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0001_initial'),
        ('productos', '0005_alter_categoria_options_alter_producto_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carrito',
            options={'ordering': ['-actualizado'], 'verbose_name': 'carrito', 'verbose_name_plural': 'carritos'},
        ),
        migrations.AlterModelOptions(
            name='itemcarrito',
            options={'ordering': ['producto__nombre'], 'verbose_name': 'ítem del carrito', 'verbose_name_plural': 'ítems del carrito'},
        ),
        migrations.AlterField(
            model_name='carrito',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carritos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='itemcarrito',
            name='cantidad',
            field=models.PositiveIntegerField(default=1, help_text='Cantidad de unidades del producto'),
        ),
        migrations.AlterField(
            model_name='itemcarrito',
            name='descripcion',
            field=models.CharField(blank=True, help_text='Descripción adicional del producto', max_length=255),
        ),
        migrations.AlterField(
            model_name='itemcarrito',
            name='precio',
            field=models.DecimalField(decimal_places=2, help_text='Precio unitario al momento de agregar al carrito', max_digits=10),
        ),
        migrations.AlterField(
            model_name='itemcarrito',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='en_carritos', to='productos.producto'),
        ),
        migrations.AddConstraint(
            model_name='itemcarrito',
            constraint=models.UniqueConstraint(fields=('carrito', 'producto'), name='unique_producto_en_carrito'),
        ),
    ]
